site_name: Simplean
site_description: Simplean dom animation javascript
site_author: liyanda
pages:
- 概览: index.md
- API: api.md
- 兼容性: compatibility.md
theme: readthedocs
repo_url: https://github.com/liyandalmllml/simplean.js.git
